export const StockActionTypes = {
  SET_ITEMS: 'SET_ITEMS',
  SET_SEARCH_STRING: 'SET_SEARCH_STRING',
  ADD_ITEM: 'ADD_ITEM',
  REMOVE_ITEM: 'REMOVE_ITEM',
  INCREASE_QTY: 'INCREASE_QTY',
  DECREASE_QTY: 'DECREASE_QTY'
}